# https://docs.travis-ci.com/user/database-setup/#postgresql
dist: xenial
sudo: true
services:
  - postgresql
addons:
  postgresql: "11"
  apt:
    packages:
    - postgresql-11
    - postgresql-client-11
    - postgresql-11-postgis


language: node_js
node_js:
- '10.15.1'

# before_script:
  # - psql -c 'create database postgres;' -U postgres
before_script:
  # running code climate
  - psql -U postgres -c "create extension postgis"
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
- npm test
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
